ALTER TABLE "hotels"
  ADD COLUMN IF NOT EXISTS "legal_entity_name" TEXT,
  ADD COLUMN IF NOT EXISTS "hotel_classification" TEXT NOT NULL DEFAULT 'other',
  ADD COLUMN IF NOT EXISTS "room_count" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "average_daily_load_kg" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "service_level" TEXT NOT NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS "operating_hours" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "peak_hours" TEXT,
  ADD COLUMN IF NOT EXISTS "requires_daily_pickup" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "address_text" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "pickup_location" TEXT,
  ADD COLUMN IF NOT EXISTS "has_loading_area" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "access_notes" TEXT,
  ADD COLUMN IF NOT EXISTS "commercial_registration_number" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "commercial_registration_file_json" JSONB,
  ADD COLUMN IF NOT EXISTS "commercial_registration_expiry_date" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "delegation_letter_file_json" JSONB,
  ADD COLUMN IF NOT EXISTS "delegation_letter_purpose_ar" TEXT,
  ADD COLUMN IF NOT EXISTS "delegation_status" TEXT NOT NULL DEFAULT 'not_provided';
